### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [1]:
# code
import numpy as np
a = np.random.randint(1,100,15)
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [2]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[12, 66,  4, 78],
       [ 9, 18, 25, 90],
       [ 7, 84, 30, 89],
       [87, 86, 95, 66],
       [34, 10,  1, 13],
       [91, 26, 56,  1]])

In [3]:
np.sort(a)[::-1]

array([98, 74, 73, 73, 70, 61, 59, 57, 52, 43, 38, 37, 27,  9,  2])

In [4]:
np.sort(b,axis=0)

array([[ 7, 10,  1,  1],
       [ 9, 18,  4, 13],
       [12, 26, 25, 66],
       [34, 66, 30, 78],
       [87, 84, 56, 89],
       [91, 86, 95, 90]])

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [5]:
# code
np.append(a,200)

array([ 59,   2,  74,   9,  38,  73,  73,  43,  98,  61,  70,  57,  52,
        37,  27, 200])

In [6]:
b

array([[12, 66,  4, 78],
       [ 9, 18, 25, 90],
       [ 7, 84, 30, 89],
       [87, 86, 95, 66],
       [34, 10,  1, 13],
       [91, 26, 56,  1]])

In [7]:
np.append(b,np.random.random((b.shape[0],1)),axis=1)

array([[1.20000000e+01, 6.60000000e+01, 4.00000000e+00, 7.80000000e+01,
        3.56455839e-01],
       [9.00000000e+00, 1.80000000e+01, 2.50000000e+01, 9.00000000e+01,
        6.15268138e-01],
       [7.00000000e+00, 8.40000000e+01, 3.00000000e+01, 8.90000000e+01,
        7.72232821e-01],
       [8.70000000e+01, 8.60000000e+01, 9.50000000e+01, 6.60000000e+01,
        6.95343912e-03],
       [3.40000000e+01, 1.00000000e+01, 1.00000000e+00, 1.30000000e+01,
        1.83113636e-01],
       [9.10000000e+01, 2.60000000e+01, 5.60000000e+01, 1.00000000e+00,
        6.09259933e-01]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [8]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [9]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [10]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [11]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [12]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [13]:
# code
a.shape

(15,)

In [14]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [15]:
np.expand_dims(a,axis=1)

array([[59],
       [ 2],
       [74],
       [ 9],
       [38],
       [73],
       [73],
       [43],
       [98],
       [61],
       [70],
       [57],
       [52],
       [37],
       [27]])

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [16]:
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [17]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 0,  2,  5,  6,  8,  9, 10, 11, 12]),)

In [18]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0,  2,  0,  9, 38,  0,  0, 43,  0,  0,  0,  0,  0, 37, 27])

In [19]:
np.where(a%2 == 0,0,a)

array([59,  0,  0,  9,  0, 73, 73, 43,  0, 61,  0, 57,  0, 37, 27])

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [20]:
# code
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [21]:
np.argmax(a)

8

In [22]:
b

array([[12, 66,  4, 78],
       [ 9, 18, 25, 90],
       [ 7, 84, 30, 89],
       [87, 86, 95, 66],
       [34, 10,  1, 13],
       [91, 26, 56,  1]])

In [23]:
np.argmax(b,axis=0)

array([5, 3, 3, 1])

In [24]:
np.argmax(b,axis=1)

array([3, 3, 3, 2, 0, 0])

In [25]:
# np.argmin
np.argmin(a)

1

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [26]:
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [27]:
np.cumsum(a)

array([ 59,  61, 135, 144, 182, 255, 328, 371, 469, 530, 600, 657, 709,
       746, 773])

In [28]:
b

array([[12, 66,  4, 78],
       [ 9, 18, 25, 90],
       [ 7, 84, 30, 89],
       [87, 86, 95, 66],
       [34, 10,  1, 13],
       [91, 26, 56,  1]])

In [29]:
np.cumsum(b,axis=1)

array([[ 12,  78,  82, 160],
       [  9,  27,  52, 142],
       [  7,  91, 121, 210],
       [ 87, 173, 268, 334],
       [ 34,  44,  45,  58],
       [ 91, 117, 173, 174]])

In [30]:
np.cumsum(b)

array([  12,   78,   82,  160,  169,  187,  212,  302,  309,  393,  423,
        512,  599,  685,  780,  846,  880,  890,  891,  904,  995, 1021,
       1077, 1078])

In [31]:
# np.cumprod
np.cumprod(a)

array([                  59,                  118,                 8732,
                      78588,              2986344,            218003112,
                15914227176,         684311768568,       67062553319664,
           4090815752499504,   286357102674965280, -2124389221236530656,
         212224937957715584,  7852322704435476608,  9098528208952800640])

In [32]:
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [33]:
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [34]:
np.percentile(a,50)

57.0

In [35]:
np.median(a)

57.0

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [36]:
# code
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [37]:
np.histogram(a,bins=[0,50,100])

(array([6, 9]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [38]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [39]:
# code
a


array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [40]:
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([70])

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [41]:
# code
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [42]:
np.flip(a)

array([27, 37, 52, 57, 70, 61, 98, 43, 73, 73, 38,  9, 74,  2, 59])

In [43]:
b

array([[12, 66,  4, 78],
       [ 9, 18, 25, 90],
       [ 7, 84, 30, 89],
       [87, 86, 95, 66],
       [34, 10,  1, 13],
       [91, 26, 56,  1]])

In [44]:
np.flip(b,axis=1)

array([[78,  4, 66, 12],
       [90, 25, 18,  9],
       [89, 30, 84,  7],
       [66, 95, 86, 87],
       [13,  1, 10, 34],
       [ 1, 56, 26, 91]])

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [45]:
# code
a

array([59,  2, 74,  9, 38, 73, 73, 43, 98, 61, 70, 57, 52, 37, 27])

In [46]:
np.put(a,[0,1],[110,530])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [47]:
# code
a

array([110, 530,  74,   9,  38,  73,  73,  43,  98,  61,  70,  57,  52,
        37,  27])

In [48]:
np.delete(a,[0,2,4])

array([530,   9,  73,  73,  43,  98,  61,  70,  57,  52,  37,  27])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [49]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [50]:
np.intersect1d(m,n)

array([3, 4, 5])

In [51]:
np.setdiff1d(n,m)

array([6, 7])

In [52]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [53]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [54]:
# code
a

array([110, 530,  74,   9,  38,  73,  73,  43,  98,  61,  70,  57,  52,
        37,  27])

In [55]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 74, 25, 38, 73, 73, 43, 75, 61, 70, 57, 52, 37, 27])

In [62]:
# 17. np.swapaxes
import numpy as np

a = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Original Shape:", a.shape)  # (2, 2, 2)

# Swap axis 0 and 1
b = np.swapaxes(a, 0, 1)

print("Swapped Array:\n", b)
print("New Shape:", b.shape)  # (2, 2, 2) but axes 0 and 1 are swapped


Original Shape: (2, 2, 2)
Swapped Array:
 [[[1 2]
  [5 6]]

 [[3 4]
  [7 8]]]
New Shape: (2, 2, 2)


In [63]:
# 18. np.uniform

# Generate a single random number between 0 and 1
print(np.random.uniform())

0.6366267779187713


In [64]:
# Generate 5 random numbers between 10 and 20
random_numbers = np.random.uniform(10, 20, 5)
print(random_numbers)

[14.94283015 17.61802632 15.5061886  16.41927497 11.36020608]


In [65]:
# Generate a 3x3 matrix of random values between -5 and 5
matrix = np.random.uniform(-5, 5, (3, 3))
print(matrix)

[[-0.64234548 -3.82002438  1.68264477]
 [ 0.73665874  0.2511795  -4.56199229]
 [-2.23022108 -2.56987927 -0.17292501]]


In [66]:
# 19. np.count_nonzero
a = np.array([0, 1, 2, 0, 3, 4, 0])
count = np.count_nonzero(a)
print(count)

4


In [67]:
a = np.array([
    [0, 1, 2],
    [3, 0, 4]
])

count = np.count_nonzero(a)
print(count)  # Output: 4


4


In [68]:
a = np.array([
    [0, 1, 2],
    [3, 0, 4]
])

count_axis0 = np.count_nonzero(a, axis=0)  # Count in each column
count_axis1 = np.count_nonzero(a, axis=1)  # Count in each row

print(count_axis0)  # Output: [1 1 2]
print(count_axis1)  # Output: [2 2]


[1 1 2]
[2 2]


In [69]:
a = np.array([True, False, True, False, True])
print(np.count_nonzero(a))  # Output: 3 (True values are nonzero)

3


In [70]:
# 21. np.tile
a = np.array([1, 2, 3])

# Repeat the array 3 times
print(np.tile(a, 3))


[1 2 3 1 2 3 1 2 3]


In [73]:
a = np.array([[1, 2], [3, 4]])

# Repeat it 2 times along rows and 3 times along columns
print(np.tile(a, (2, 3)))

[[1 2 1 2 1 2]
 [3 4 3 4 3 4]
 [1 2 1 2 1 2]
 [3 4 3 4 3 4]]


In [74]:
# 22. np.repeat
a = np.array([1, 2, 3])

# Repeat each element 2 times
print(np.repeat(a, 2))

[1 1 2 2 3 3]


In [75]:
a = np.array([[1, 2], [3, 4]])

# Repeat along axis 0 (rows)
print(np.repeat(a, 2, axis=0))

# Repeat along axis 1 (columns)
print(np.repeat(a, 2, axis=1))


[[1 2]
 [1 2]
 [3 4]
 [3 4]]
[[1 1 2 2]
 [3 3 4 4]]


In [76]:
# 25. np.allclose and equals
a = np.array([1.0, 2.000001, 3.0])
b = np.array([1.0, 2.0, 3.0])

# Allow small floating-point differences
print(np.allclose(a, b))

True


In [77]:
a = np.array([1.0, 2.000001, 3.0])
b = np.array([1.0, 2.0, 3.0])

# Strict comparison
print(np.array_equal(a, b))

False


In [71]:
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [72]:
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5